[package]
name = "hadal"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
env_logger = "0.11.11"
log = "0.4.34"
thiserror = "2.0.21"
wgpu = "30.0.1"
winit = "0.30.13"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

unwrap_used = "warn"
expect_used = "warn"
